# Generated by Django 4.1.1 on 2022-10-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despesa', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=10)),
                ('data', models.IntegerField()),
                ('mes', models.IntegerField()),
            ],
        ),
    ]
